---
- name: Update Centos, install MySQL, Nginx, PHP-FPM, and TestLink
  hosts: testlink
  become: true
  roles:
    - system
    - php-fpm
    - nginx
    - mysql
    - testlink
    - company_settings
